# Generated by Django 4.0.1 on 2022-01-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tag_project_votes_ratio_project_votes_total_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='votes_ratio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='votes_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
